use_small_heuristics = "Max"   # prefer breaking earlier
normalize_comments = true
use_field_init_shorthand = true
newline_style = "Unix"
style_edition = "2024"
array_width = 60

unstable_features = true
imports_granularity = "Crate"  # consolidate use by crate
reorder_imports = true         # required to merge imports
imports_layout = "Vertical"    # one per line in braces (if any)